services:
  # Base image containing dependencies.
  base:
    image: turtlebot3:base
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    privileged: True
    environment:
      # Needed to define a TurtleBot3 model type
      - TURTLEBOT3_MODEL=${TURTLEBOT3_MODEL:-burger}
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority

  # Overlay image containing the example source code.
  overlay:
    extends: base
    image: turtlebot3:overlay
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: overlay

  # Developer container
  dev:
    extends: overlay
    image: turtlebot3:dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
      args:
        - UID=${UID:-1000}
        - GID=${UID:-1000}
        - USERNAME=${USERNAME:-devuser}
    volumes:
      # Mount the source code
      - ./turtlebot_commander:/overlay_ws/turtlebot_commander/
      - ./chatter:/overlay_ws/chatter/

      # Mount colcon build artifacts for faster rebuilds
      - ./.colcon/build/:/overlay_ws/.colcon/build/:rw
      - ./.colcon/install/:/overlay_ws/.colcon/install/:rw
      - ./.colcon/log/:/overlay_ws/.colcon/log/:rw
    user: ${USERNAME:-devuser}
    command: bash 

  # Runs basic TurtleBot3 simulation
  sim:
    extends: overlay
    command: ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py

  # Runs TurtleBot3 with Cartographer
  cartographer:
    extends: overlay
    command: ros2 launch turtlebot3_cartographer cartographer.launch.py

  # Teleop
  teleop:
    extends: overlay
    command: python3 /overlay_ws/turtlebot_commander/tools/teleop/main.py

  # Commander
  commander:
    extends: overlay
    command: ros2 launch turtlebot_commander turtlebot_commander.launch.py

  # Chatter
  chatter:
    extends: overlay
    command: python3 /overlay_ws/chatter/main.py
